language: node_js

before_script:
  - psql -U postgres -c "CREATE USER test WITH PASSWORD 'dbpass';"
  - psql -U postgres -c "CREATE DATABASE test WITH OWNER test;"

env:
  - DATABASE_URL: "postgresql://test:dbpass@localhost:5432/test"

script:
  - make package
  - node_modules/.bin/mocha --reporter tap
  - make lint

matrix:
  include:
    - node_js: "0.10"
      addons:
        postgresql: "9.1"
    - node_js: "0.10"
      addons:
        postgresql: "9.2"
    - node_js: "0.10"
      addons:
        postgresql: "9.3"
    - node_js: "0.10"
      addons:
        postgresql: "9.4"
    - node_js: "0.10"
      addons:
        postgresql: "9.5"
    - node_js: "0.12"
      addons:
        postgresql: "9.1"
    - node_js: "0.12"
      addons:
        postgresql: "9.2"
    - node_js: "0.12"
      addons:
        postgresql: "9.3"
    - node_js: "0.12"
      addons:
        postgresql: "9.4"
    - node_js: "0.12"
      addons:
        postgresql: "9.5"
    - node_js: "stable"
      addons:
        postgresql: "9.2"
    - node_js: "stable"
      addons:
        postgresql: "9.3"
    - node_js: "stable"
      addons:
        postgresql: "9.4"
    - node_js: "stable"
      addons:
        postgresql: "9.5"
    - node_js: "5"
      addons:
        postgresql: "9.2"
    - node_js: "5"
      addons:
        postgresql: "9.3"
    - node_js: "5"
      addons:
        postgresql: "9.4"
    - node_js: "5"
      addons:
        postgresql: "9.5"
